### ISSUE TITLE
[Bug] Error while using NEHVI with deterministic models

### ISSUE THREAD

**Issue by saitcakmak** [pytorch/botorch#966] opened 2021-11-03 18:53 UTC
# 🐛 Bug

The `_set_sampler()` method of `qNEHVI` throws an `IndexError` when used with a `DeterministicModel` due to `model.base_sample_shape` returning `torch.Size()`. Prior to #829,  `model.base_sample_shape` would return `model.event_shape` and the code would run without any issues.

## To reproduce

** Code snippet to reproduce **
```python
import torch
from botorch.acquisition.multi_objective.monte_carlo import qNoisyExpectedHypervolumeImprovement
from botorch.models.deterministic import GenericDeterministicModel
from botorch.sampling import IIDNormalSampler

ref_point = torch.tensor([-1, -2])
train_X = torch.rand(10, 2)
det_model = GenericDeterministicModel(lambda X: X)

acqf = qNoisyExpectedHypervolumeImprovement(
    model=det_model,
    ref_point=ref_point,
    X_baseline=train_X,
    sampler=IIDNormalSampler(1),
)
posterior = acqf.model.posterior(train_X)
q = train_X.shape[-2]
print(f"Event shape: {posterior.event_shape}, base sample shape: {posterior.base_sample_shape}")
acqf._set_sampler(q=q, posterior=posterior)
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/Users/saitcakmak/PycharmProjects/robust_mobo/debug/nehvi_deterministic_posterior_bug.py", line 19, in <module>
    acqf._set_sampler(q=q, posterior=posterior)
  File "/opt/anaconda3/envs/robust_mobo/lib/python3.9/site-packages/botorch/acquisition/multi_objective/monte_carlo.py", line 672, in _set_sampler
    end_idx = current_base_samples.shape[-2]
IndexError: tuple index out of range
Event shape: torch.Size([10, 2]), base sample shape: torch.Size([])
```

## Expected Behavior

Should run without errors. The base sample shape needs to be the same as the event shape for the NEHVI methods to work properly.

## System information

**Please complete the following information:**
BoTorch: Current main branch.

## Additional Context

The code to reproduce is a stripped out version of the code for running NEHVI with RFFs. This error currently prevents running NEHVI with RFFs on the main branch.

cc @sdaulton, @Balandat

**Comment by sdaulton** [comment] 2021-11-03 20:10
Thanks for catching that. In the interim, qEHVI and qNEHVI are equivalent with a deterministic model (as long as you reconstruct the partitioning and qEHVI acquisition function after selecting each point in the q-batch during sequential greedy batch generation)

**Comment by saitcakmak** [comment] 2021-12-09 01:38
Bumping this since I've been running into the same issue elsewhere. 

@Balandat, was there a reason for adding this and overwriting the default `self.event_shape`?

https://github.com/Balandat/botorch/blob/9122d0ac12bceb8a2181874ac46d159ca2435a3e/botorch/posteriors/deterministic.py#L27-L35

If not, I'd like to revert this. This ends up being used in the samplers

https://github.com/Balandat/botorch/blob/9122d0ac12bceb8a2181874ac46d159ca2435a3e/botorch/sampling/samplers.py#L91-L92

which both leads to the sampler recording faulty `base_sample_shape` and using this faulty shape to generate the samples in 

https://github.com/Balandat/botorch/blob/9122d0ac12bceb8a2181874ac46d159ca2435a3e/botorch/sampling/samplers.py#L301-L307

which may lead to similar issues as in #504.

Currently, I'm getting around this by replacing the `samples = sampler(posterior)` with
```
if isinstance(posterior, DeterministicPosterior):
    base_sample_shape = (
        self.sampler.sample_shape + posterior.event_shape
    )
else:
    base_sample_shape = self.sampler._get_base_sample_shape(
        posterior=posterior
    )
self.sampler._construct_base_samples(
    posterior=posterior, shape=base_sample_shape
)
samples = posterior.rsample(
    sample_shape=self.sampler.sample_shape,
    base_samples=self.sampler.base_samples,
)
```

**Comment by Balandat** [comment] 2021-12-09 02:32
Is the issue here that the `_set_sampler` code is written with the assumption that the `base_sample_shape` is equal to the `event_shape` of the posterior? 

It seems logical to me that a `DeterministicPosterior` by definition doesn't require any base samples. Similarly, this shape discrepancy also comes up in the context of implementing Matheron's rule sampling for some of the MTGP work with @wjmaddox, where we essentially need a tensor of base samples that is of different size than the event shape of the posterior (cc @jtwilson), though that is unrelated to the issues with the `DeterministicPosterior`. 

This heterogeneity in shapes is also used / honored when combining different kinds of `Posterior` objects into a `PosteriorList` (e.g. [here](https://github.com/pytorch/botorch/blob/385ed23db49340703c0e595da6b55ba9181baf9f/botorch/posteriors/posterior.py#L129-L132)). 

> leads to the sampler recording faulty base_sample_shape

What exactly do you mean by "faulty"? My take would be that `DeterministicPosterior` by definition should never require any base samples. We could of course generate some but this seems logically a bit inconsistent (and would also not work for the Matheron sampling case).

**Comment by saitcakmak** [comment] 2021-12-09 03:52
> Is the issue here that the _set_sampler code is written with the assumption that the base_sample_shape is equal to the event_shape of the posterior?

Digging a bit more into it, that does seem to be the issue here. `_set_sampler` expects the base samplers to have shape `mc_samples x event_shape`, which doesn't work with `DeterministicPosterior` since they end up with shape `mc_samples`. Maybe we should simply make `_set_sampler` a no-op if the posterior is deterministic? @sdaulton 

> My take would be that DeterministicPosterior by definition should never require any base samples.

That does make sense. Since there's no randomness, you should not need any samples.

**Comment by Balandat** [comment] 2022-02-08 01:57
I believe this has been resolved via #1037? Feel free to reopen if still an issue.

**Closed by Balandat** 2022-02-08 01:57 UTC
Labels: bug

**Comment by GabrielUribe29** [comment] 2025-01-30 14:37
I am commenting on this issue because I believe the problem persists. I am using **ModelList** with both a probabilistic and a deterministic model. 

**code snippet for verification:**

`import botorch
import numpy
import pandas
import os
import torch

from botorch.models.gp_regression import SingleTaskGP
from botorch.models.transforms.outcome import Standardize
from botorch. models import ModelList
from botorch.models.deterministic import GenericDeterministicModel
from torch import Tensor
from typing import Callable

from botorch.acquisition.multi_objective.monte_carlo import qExpectedHypervolumeImprovement, qNoisyExpectedHypervolumeImprovement
from botorch.optim.optimize import optimize_acqf, optimize_acqf_list
from botorch.utils.multi_objective.box_decompositions.non_dominated import FastNondominatedPartitioning
from botorch.sampling import SobolQMCNormalSampler
from botorch.utils.transforms import unnormalize, normalize
from botorch.utils.multi_objective import infer_reference_point


train_X = torch.rand(20, 4, dtype=torch.float64)
train_Y1 = torch.sin(train_X).sum(dim=1, keepdim=True)
def Cos(X):
    mean=torch.cos(train_X).sum(dim=1, keepdim=True)
    return mean
train_Y2=Cos(train_X)
train_Y=torch.cat([train_Y1,train_Y2], axis=1)


outcome_transform = Standardize(m=1)
train_Yvar = torch.full_like(train_Y1, 0.2)
Probabilistic_model = SingleTaskGP(train_X, train_Y1, train_Yvar,outcome_transform=outcome_transform)

Deterministic_model=GenericDeterministicModel(Cos)

model=ModelList(Deterministic_model, Probabilistic_model)

bounds=torch.stack([torch.zeros(4, dtype=torch.float64), 
                      torch.ones(4, dtype=torch.float64)])

ref_point = infer_reference_point(train_Y)

with torch.no_grad():
        pred = model.posterior(normalize(train_X, bounds)).mean
        partitioning = FastNondominatedPartitioning(
        ref_point=ref_point, 
        Y=pred,
    )

acq_func = qExpectedHypervolumeImprovement(
        model=model,
        ref_point=ref_point,
        partitioning=partitioning,
        sampler=SobolQMCNormalSampler(torch.Size([256])),
        
    )

candidate, _ = optimize_acqf(acq_func, 
                             bounds=bounds, 
                             q=1, 
                             num_restarts=10, 
                             raw_samples=256)`
**Error message**

NotImplementedError: PosteriorList does not implement `base_sample_shape`.

**Comment by saitcakmak** [comment] 2025-01-30 14:53
Hi @GabrielUribe29. `SobolQMCNormalSampler` is not compatible with `PosteriorList`. You can construct an appropriate `ListSampler` using the `get_sampler` (under `botorch/sampling/get_sampler.py`) helper.
