### ISSUE TITLE
Unable to reproduce the source codes from https://github.com/facebookresearch/preference-exploration

### ISSUE THREAD

**Issue by wwwccttoo** [pytorch/botorch#1897] opened 2023-06-20 23:21 UTC
To whom it may concern,

I am pretty interested in using perference based BO. However, when I am trying to directly run the source codes from https://github.com/facebookresearch/preference-exploration to reproduce some examples, I found significant mismatches.
I have tested one example (OSY_piecewiselinear) on both newest and required (0.6) Botorch version, as well as on different platforms (windows and Ubuntu), and using CPU and GPU. However, none of then can reach the values reported in the paper. Moreover, on unbuntu with the newest version, almost no improvement can be observed.

Tested Example details
OSY_6d8d_piecewiselinear, EUBO_rff and EUBO_zeta, random initialize (random_ps), noisy=False, kernel='default', comp_noise_type='constant'. Totaly 30 inital X sets are used to generate the mean and std as what has been done in the paper (the mean and std of batch 1 are the same therefore).
This setting is used based on the "run_multi_sim.sh", where: "CUDA_VISIBLE_DEVICES=$gpu nice -n 19 python multi_batch_sim.py --problem_str=$problem_str --noisy=False --init_seed=$i --kernel=default --comp_noise_type=$cnt --device=$gpu"

Paper, **EUBO_rff**:
mean [-14.7289, -12.1780, -10.4689, -9.2164], std [4.1320, 1.6839, 1.3421, 1.1998]
Ubuntu 20.04.6, BoTorch 0.8.5, GPyTorch 1.10, PyTorch 2.0.1+cpu, running on CPU:
mean [-14.7289, -14.5101, -14.3574, -14.0330], std [4.1320, 4.3157, 4.2119, 3.9256]
Ubuntu 20.04.6, BoTorch 0.6.0, GPyTorch 1.6, PyTorch 1.9.0+cu102, running on CPU:
mean [-14.7289, -14.5085, -12.7374, -10.3477], std [4.1320, 3.6059, 2.0797, 1.6009]
Windows 11, BoTorch 0.8.5, GPyTorch 1.10, PyTorch 2.0.1+cu117, running on CPU:
mean [-14.7289, -13.4052, -12.6236, -12.0827], std [4.1320, 2.8711, 2.2296, 2.3816]
Windows 11, BoTorch 0.8.5, GPyTorch 1.10, PyTorch 2.0.1+cu117, running on GPU (3060 6GB):
mean [-14.7289, -13.4472, -12.4805, -11.8908], std [4.1320, 2.7614, 2.6707, 2.4635]

Paper, **EUBO_zeta**:
mean [-14.7289, -12.3112, -10.7266, -9.4325], std [4.1320, 1.5436, 1.0772, 1.0014]
Ubuntu 20.04.6, BoTorch 0.8.5, GPyTorch 1.10, PyTorch 2.0.1+cpu, running on CPU:
under [-14.7289, -14.7289, -14.6044, -12.9211], std [4.1320, 4.1320, 4.1889, 2.8885]
Ubuntu 20.04.6, BoTorch 0.6.0, GPyTorch 1.6, PyTorch 1.9.0+cu102, running on CPU:
mean [-14.7289, -14.0955, -12.2165, -10.6349], std [4.1320, 3.0928, 1.9879, 2.2803]
Windows 11, BoTorch 0.8.5, GPyTorch 1.10, PyTorch 2.0.1+cu117, running on CPU:
mean [-14.7289, -13.6264, -11.4118, -10.2132], std [4.1320, 3.1180, 1.5770, 1.2939]
Windows 11, BoTorch 0.8.5, GPyTorch 1.10, PyTorch 2.0.1+cu117, running on GPU (3060 6GB):
mean [-14.7289, -13.8689, -11.7422, -10.3396], std [4.1320, 3.9462, 2.2743, 1.4490]

In Windows, either cpu or gpu actually gives the same results, however, still worse than the values reported. This means run results averaged under 30 runs should be stable and reproducible.

And I found significant degradation of performance in Ubuntu using the newest versions of packages. Again, even installing the packages following the requirements.txt can still not give the same results.

I am not sure if I used any arguments wrongly or there is anything I am missing. I was wondering if you could help me on this. 

Many thanks!

**Comment by saitcakmak** [comment] 2023-06-20 23:30
Hi @wwwccttoo. This sounds like an issue better raised directly on the preference-exploration repo since it relates to code that lives outside of BoTorch. cc @ItsMrLin @RaulAstudillo06

**Comment by wwwccttoo** [comment] 2023-06-21 03:12
> Hi @wwwccttoo. This sounds like an issue better raised directly on the preference-exploration repo since it relates to code that lives outside of BoTorch. cc @ItsMrLin @RaulAstudillo06

Thanks for your quick reply! 
I think it is still relevant to Botorch since pairwiseGP and EUBO are now parts of Botorch, which have been updated since Botorch 0.6.

**Comment by ItsMrLin** [comment] 2023-06-21 17:21
Hi @wwwccttoo, thanks for reaching out. As @saitcakmak said, this does seem to be more related to the paper repo rather than the BoTorch repo.

That said, the `PairwiseGP` model has been updated since the publication of the paper to improve its numerical stability including the usage of an update prior. Considering the model difference on top of the underlying packages (the scipy optimizer used under the hood) and OS differences, I wouldn't be too surprised to see the results don't match exactly (though it is surprising that PairwiseGP's performance looks worse in the latest BoTorch).

Have you tried other baselines? IIRC, the OSY baseline can have outcomes in very different scales, which may make the results more sensitive to variations. Looking at your std (assuming they are SE of the mean), the original results are still within the range of 95% CI (even for 50% for most of them). The fact that we are propagating the uncertainty through 2 instead of 1 model unfortunately may lead to inflated variances in the results compared to regular BO.

I'm closing this issue as this is not directly related to the BoTorch package itself. I just saw that you sent us an email (landed in the junk folder, sorry!), and I'm happy to continue the discussion there if it is important to reproduce the exact numbers. 🙂

**Closed by ItsMrLin** 2023-06-21 17:21 UTC
