### ISSUE TITLE
When the initial points go larger, the nan problem happens 

### ISSUE THREAD

**Issue by PMY0124** [pytorch/botorch#1437] opened 2022-10-02 12:56 UTC
# 🐛 Bug

Stack trace/error message
Traceback (most recent call last):
  File "/home/whw/pmy/7-BO-PGExplainer-gpu-accuracy/script.py", line 91, in <module>
    X,Y = exp.one_iteration(acqf=ExpectedImprovement)
  File "/home/whw/pmy/7-BO-PGExplainer-gpu-accuracy/boPG.py", line 286, in one_iteration
    candidate, value = optimize_acqf(
  File "/home/whw/anaconda3/envs/torch-1.11-3.10/lib/python3.10/site-packages/botorch/optim/optimize.py", line 238, in optimize_acqf
    batch_initial_conditions = ic_gen(
  File "/home/whw/anaconda3/envs/torch-1.11-3.10/lib/python3.10/site-packages/botorch/optim/initializers.py", line 194, in gen_batch_initial_conditions
    Y_rnd_curr = acq_function(
  File "/home/whw/anaconda3/envs/torch-1.11-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/whw/anaconda3/envs/torch-1.11-3.10/lib/python3.10/site-packages/botorch/utils/transforms.py", line 270, in decorated
    output = method(acqf, X, *args, **kwargs)
  File "/home/whw/anaconda3/envs/torch-1.11-3.10/lib/python3.10/site-packages/botorch/acquisition/analytic.py", line 146, in forward
    ucdf = normal.cdf(u)
  File "/home/whw/anaconda3/envs/torch-1.11-3.10/lib/python3.10/site-packages/torch/distributions/normal.py", line 81, in cdf
    self._validate_sample(value)
  File "/home/whw/anaconda3/envs/torch-1.11-3.10/lib/python3.10/site-packages/torch/distributions/distribution.py", line 286, in _validate_sample
    raise ValueError(
ValueError: Expected value argument (Tensor of shape (5,)) to be within the support (Real()) of the distribution Normal(loc: torch.Size([5]), scale: torch.Size([5])), but found invalid values:
tensor([nan, nan, nan, nan, nan], device='cuda:1')

## System information

- BoTorch Version 0.7.2 
- GPyTorch Version 1.9.0
-  PyTorch Version 1.11.0

**Comment by eytan** [comment] 2022-10-02 13:34
Can you please include a code snippet to reproduce the error?

**Comment by PMY0124** [comment] 2022-10-02 14:25
I still don't know what happened, but I use double type rather than float type, and the problem seems disappear!

**Comment by Balandat** [comment] 2022-10-02 15:21
> I still don't know what happened, but I use double type rather than float type, and the problem seems disappear!

Likely your training data is such that the involved covariance are quite ill-conditioned so that you're running into numerical accuracy issues with float that produce NaNs. This is pretty common when using GPs and unless you have a good reason (e.g. you want to save GPU memory or you really need the faster float processing on some models) I would recommend always using double.

**Comment by Balandat** [comment] 2022-10-02 15:22
I'm going to close this with the understanding that this is not a bug but just a numerical issue. Feel free to reopen if needed.

**Closed by Balandat** 2022-10-02 15:22 UTC
Labels: bug
