### ISSUE TITLE
[question] How to swap a model inferring noise as suggested in tutorial

### ISSUE THREAD

**Issue by alinaselega** [pytorch/botorch#1030] opened 2021-12-09 21:40 UTC
In this [tutorial](https://botorch.org/tutorials/multi_objective_bo), it is noted that one could use `SingleTaskGP` instead of `FixedNoiseGP` in order to infer homoscedastic noise. When I substitute as suggested in the `initialize_model()`, I get this error when running the cell with the BO loop:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-34-8ce255746951> in <module>()
     30     # call helper functions to generate initial training data and initialize model
     31     train_x_qparego, train_obj_qparego, train_obj_true_qparego = generate_initial_data(n=2*(problem.dim+1))
---> 32     mll_qparego, model_qparego = initialize_model(train_x_qparego, train_obj_qparego)
     33 
     34     train_x_qehvi, train_obj_qehvi, train_obj_true_qehvi = train_x_qparego, train_obj_qparego, train_obj_true_qparego
...
/usr/local/lib/python3.7/dist-packages/gpytorch/models/exact_gp.py in __init__(self, train_inputs, train_targets, likelihood)
     59             raise RuntimeError("Train inputs must be a tensor, or a list/tuple of tensors")
     60         if not isinstance(likelihood, _GaussianLikelihoodBase):
---> 61             raise RuntimeError("ExactGP can only handle Gaussian likelihoods")
     62 
     63         super(ExactGP, self).__init__()

RuntimeError: ExactGP can only handle Gaussian likelihoods
```

The modified `initialized_model()` is:

```
def initialize_model(train_x, train_obj):
    # define models for objective and constraint
    train_x = normalize(train_x, problem.bounds)
    models = []
    for i in range(train_obj.shape[-1]):
        train_y = train_obj[..., i:i+1]
        train_yvar = torch.full_like(train_y, NOISE_SE[i] ** 2)
        models.append(
            SingleTaskGP(train_x, train_y, train_yvar, outcome_transform=Standardize(m=1))
        )
    model = ModelListGP(*models)
    mll = SumMarginalLogLikelihood(model.likelihood, model)
    return mll, model
```

If instead I use `SingleTaskGP` without `ModelListGP` (as was used in the [previous version of this tutorial](https://botorch.org/v/0.5.1/tutorials/multi_objective_bo)), then the error is raised when computing new candidates with `optimize_qnehvi_and_get_observation()` (notably, the steps with qEHVI and qNParEGO compute without error):

```
BotorchError                              Traceback (most recent call last)
<ipython-input-39-8ce255746951> in <module>()
     70         )
     71         new_x_qnehvi, new_obj_qnehvi, new_obj_true_qnehvi = optimize_qnehvi_and_get_observation(
---> 72             model_qnehvi, train_x_qnehvi, train_obj_qnehvi, qnehvi_sampler
     73         )
     74         new_x_random, new_obj_random, new_obj_true_random = generate_initial_data(n=BATCH_SIZE)

...
/usr/local/lib/python3.7/dist-packages/botorch/utils/low_rank.py in extract_batch_covar(mt_mvn)
     34     lazy_covar = mt_mvn.lazy_covariance_matrix
     35     if not isinstance(lazy_covar, BlockDiagLazyTensor):
---> 36         raise BotorchError(f"Expected BlockDiagLazyTensor, but got {type(lazy_covar)}.")
     37     return lazy_covar.base_lazy_tensor
     38 

BotorchError: Expected BlockDiagLazyTensor, but got <class 'gpytorch.lazy.matmul_lazy_tensor.MatmulLazyTensor'>.
```

In this case, `initialized_model()` is:
```
def initialize_model(train_x, train_obj):
    # define models for objective and constraint
    model = SingleTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    return mll, model
```

How do I use qNEHVI with `SingleTaskGP`?

Thanks!

**Comment by alinaselega** [comment] 2021-12-09 21:43
Sorry, I didn't mean to add a "bug" label.

**Comment by saitcakmak** [comment] 2021-12-09 21:55
Hi @alinaselega. The issue is that you're passing in `train_yvar` to `SingleTaskGP`, which it does not expect. It ends up being interpreted as a `likelihood`, which leads to the error about non-Gaussian likelihoods. If you remove `train_yvar` from the `SingleTaskGP(train_x, train_y, train_yvar, outcome_transform=Standardize(m=1))` call, it should work.

**Comment by alinaselega** [comment] 2021-12-09 21:59
Thanks a lot @saitcakmak! I missed that arg.

**Comment by roussel-ryan** [comment] 2022-05-11 00:10
This is still a bug with the Standardize() outcome transform, reproduced below
```
import torch
from botorch.acquisition.multi_objective import qNoisyExpectedHypervolumeImprovement
from botorch.models import SingleTaskGP
from botorch.models.transforms import Standardize
from botorch.sampling import IIDNormalSampler
from gpytorch.mlls import ExactMarginalLogLikelihood

train_x = torch.randn(3, 3)
train_y = torch.randn(3, 2)
test_x = torch.randn(3, 3)
X_baseline = torch.randn(2, 3)

model = SingleTaskGP(train_x, train_y, outcome_transform=Standardize(m=2))
mll = ExactMarginalLogLikelihood(model.likelihood, model)

ref = torch.ones(2)
sampler = IIDNormalSampler(num_samples=1)
acq = qNoisyExpectedHypervolumeImprovement(
    model,
    X_baseline=X_baseline,
    ref_point=ref,
    sampler=sampler,
)

A fix for this would be very helpful

**Comment by roussel-ryan** [comment] 2022-05-11 16:28
The bug seems to be with the transformed posterior returned by Standardize that has a MatmulLazyTensor for the lazy_covariance_matrix instead of a BlockDiagLazyTensor.

**Comment by saitcakmak** [comment] 2022-05-11 16:44
Yeah, I was looking into it a bit last night. The transformed lazy covar is a `MatmulLazyTensor` which is a product of `DiagLazyTensor @ BlockDiagLazyTensor @ DiagLazyTensor`. The current implementation of `cached_cholesky / low_rank` seems to make a strong assumption on the lazy covariance matrix of an MTMVN being a `BlockDiagLazyTensor`, and makes this assumption in multiple places. I'm looking into how to get around this and make qNEHVI work with Standardize while caching the root.

In the mean time, a simple workaround is to pass `cache_root=False` while constructing `qNEHVI`. It will be slower than what you'd have with cached root but it should work.

**Comment by Balandat** [comment] 2022-05-11 20:19
> Yeah, I was looking into it a bit last night. The transformed lazy covar is a MatmulLazyTensor which is a product of DiagLazyTensor @ BlockDiagLazyTensor @ DiagLazyTensor. The current implementation of cached_cholesky / low_rank seems to make a strong assumption on the lazy covariance matrix of an MTMVN being a MTMVN, and makes this assumption in multiple places.

One thing we may want to do here is to modify the gpytorch LazyTensor code to have`DiagLazyTensor @ BlockDiagLazyTensor` and `BlockDiagLazyTensor @ DiagLazyTensor` operations both return a `BlockDiagLazyTensor` object. This should generally be what we want in this situation and would work with the current setup. 

That said, we should probably also avoid the assumption that the `MTMVN` is a `BlockDiagLazyTensor`, that's not great.

**Comment by saitcakmak** [comment] 2022-05-11 20:59
> One thing we may want to do here is to modify the gpytorch LazyTensor code to haveDiagLazyTensor @ BlockDiagLazyTensor and BlockDiagLazyTensor @ DiagLazyTensor operations both return a BlockDiagLazyTensor object. This should generally be what we want in this situation and would work with the current setup.

Yeah, that'd be a good way to fix this. I didn't feel like touching lazy tensor code, so I fixed this at `Standardize`: #1215

> That said, we should probably also avoid the assumption that the MTMVN is a BlockDiagLazyTensor, that's not great.

This was my first attempt, but it wasn't easy to get around it. I requires checking the type of the lazy tensor in multiple places and pretty much rewriting `sample_cached_cholesky`. cc @sdaulton

**Comment by Balandat** [comment] 2022-05-11 21:53
> I didn't feel like touching lazy tensor code

Does that mean you were being lazy, or *not* lazy?  

Let me take a look at the Lazies.

**Comment by Balandat** [comment] 2022-05-11 22:33
This should help: https://github.com/cornellius-gp/gpytorch/pull/2007

**Closed** 2022-07-14 22:31 UTC
Labels: bug
