### ISSUE TITLE
[Bug] Acquisition function optimization leading to Nan grad

### ISSUE THREAD

**Issue by ruhanaazam** [pytorch/botorch#2070] opened 2023-10-25 00:18 UTC
# 🐛 Bug
I have a bayesian optimization training loop which occasionally leads to the gradient being `NaN`. Any guidance or hints will be appreciated!

## To reproduce
Below, I've filled out a certain set of training values that don't converge. When I change my device to cpu, I don't get this issue so I'm not sure if the code below will fully reproduce on other machines.

** Code snippet to reproduce **
```python
import torch
import botorch
from botorch.fit import fit_gpytorch_mll
from botorch.models.transforms import Standardize, Normalize
from gpytorch.mlls import ExactMarginalLogLikelihood
from botorch.acquisition import qExpectedImprovement
from botorch.models.gp_regression import SingleTaskGP
from botorch.optim import optimize_acqf

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

standard_bounds = torch.zeros(2, 2, device=device, dtype=torch.float64)
standard_bounds[1] = 1

train_x = torch.tensor([[0.2677, 0.3618],
        [0.8434, 0.9918],
        [0.6499, 0.1275],
        [0.2071, 0.5073],
        [0.1179, 0.1188],
        [0.5520, 0.7464],
        [0.9877, 0.3841],
        [0.4364, 0.7624],
        [0.4843, 0.1961],
        [0.9086, 0.5754]], dtype=torch.float64, device=device)
train_y = torch.tensor([[  49.4111],
        [ 885.0878],
        [  97.7627],
        [ -11.5323],
        [  89.8049],
        [-212.3698],
        [-521.6794],
        [-324.3332],
        [ 188.4020],
        [-484.3525]], dtype=torch.float64, device=device)

model = SingleTaskGP(
        train_x, 
        train_y,
        outcome_transform=Standardize(m=1),
        input_transform=Normalize(train_x.shape[-1]) #input transform to normalize not there since data already normalized...
        )
mll = ExactMarginalLogLikelihood(
            model.likelihood, model)
fit_gpytorch_mll(mll)

torch.manual_seed(5)
qEI = qExpectedImprovement(model=model,best_f=train_y.max())
normalized_candidates, acqf_values = optimize_acqf(qEI, 
                                                   standard_bounds, 
                                                   q=10, 
                                                   num_restarts=2, 
                                                   raw_samples=16, 
                                                   return_best_only=False,
                                                   options={"batch_limit": 1, "maxiter": 10, "seed": 0}) 
```

** Stack trace/error message **
```
  File "issue_reproduce.py", line 47, in <module>
    normalized_candidates, acqf_values = optimize_acqf(qEI, 
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/botorch/optim/optimize.py", line 544, in optimize_acqf
    return _optimize_acqf(opt_acqf_inputs)
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/botorch/optim/optimize.py", line 573, in _optimize_acqf
    return _optimize_acqf_batch(
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/botorch/optim/optimize.py", line 351, in _optimize_acqf_batch
    batch_candidates, batch_acq_values, ws = _optimize_batch_candidates(timeout_sec)
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/botorch/optim/optimize.py", line 335, in _optimize_batch_candidates
    ) = opt_inputs.gen_candidates(
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/botorch/generation/gen.py", line 232, in gen_candidates_scipy
    res = minimize_with_timeout(
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/botorch/optim/utils/timeout.py", line 80, in minimize_with_timeout
    return optimize.minimize(
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 696, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/scipy/optimize/_lbfgsb_py.py", line 359, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 285, in fun_and_grad
    self._update_fun()
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/scipy/optimize/_optimize.py", line 76, in __call__
    self._compute_if_needed(x, *args)
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/scipy/optimize/_optimize.py", line 70, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/dfs/scratch0/ruhana/miniconda3/envs/python3.8/lib/python3.8/site-packages/botorch/generation/gen.py", line 201, in f_np_wrapper
    raise RuntimeError(msg)
RuntimeError: 20 elements of the 20 element gradient array `gradf` are NaN. This often indicates numerical issues.
```

## Expected Behavior
Gradients should not be Nan. Expected behavior is no error message.

## System information
**Please complete the following information:**
Botorch: 0.8.5
GPyTorch: 1.10
Pytorch: 2.0.1
Ubuntu 20.04
Python: 3.8.10

**Comment by Balandat** [comment] 2023-10-25 04:11
Hmm it is odd that you don't get the issue on the CPU. That said, it's a relatively common issue that expected improvement ends up with vanishing gradients due to numerical issues. Thankfully we have a solution for it, it's called `qLogExpectedImprovement` and you can use it like a drop in replacement of `qExpectedImprovement`: https://github.com/pytorch/botorch/blob/58da9709576ed9d1febc05929e92bc11c9995399/botorch/acquisition/logei.py#L140

Try it out and feel free to flag here if you're still getting these numerical issues.

To read how and why it works, you can check out our paper: https://openreview.net/forum?id=1vyAG6j9PE (soon to be on ArXiv - cc @SebastianAment)

**Comment by RuhanaAzam** [comment] 2023-10-26 22:27
> Hmm it is odd that you don't get the issue on the CPU. That said, it's a relatively common issue that expected improvement ends up with vanishing gradients due to numerical issues. Thankfully we have a solution for it, it's called `qLogExpectedImprovement` and you can use it like a drop in replacement of `qExpectedImprovement`:
> 
> https://github.com/pytorch/botorch/blob/58da9709576ed9d1febc05929e92bc11c9995399/botorch/acquisition/logei.py#L140
> 
> Try it out and feel free to flag here if you're still getting these numerical issues.
> 
> To read how and why it works, you can check out our paper: https://openreview.net/forum?id=1vyAG6j9PE (soon to be on ArXiv - cc @SebastianAment)

@Balandat Thanks for the response, I didn't realize this was a common issue. 
When I used qLogExpectedImprovement, it still get numerical stability issues for many of the seeds. Are there ways to handle this?  

Fyi, the OpenReview link seems to be private, but I'd be interested in learning more.

**Comment by Balandat** [comment] 2023-10-26 22:42
> When I used qLogExpectedImprovement, it still get numerical stability issues for many of the seeds. Are there ways to handle this?

Hmm interesting, I wonder if the model fits are terrible (though the input data looks relatively benign). @SebastianAment would you be able to take a quick look based on the repro above? 

> Fyi, the OpenReview link seems to be private, but I'd be interested in learning more.

Should be on ArXiv very soon!

**Comment by RuhanaAzam** [comment] 2024-01-23 00:28
Fixed from downgrading to botorch `v0.8.3`.

**Comment by Balandat** [comment] 2024-01-23 01:28
Reopening this since it is problematic if these issues only appear on `0.8.5` but not on `0.8.3`. @RuhanaAzam were the rest of the dependencies in the environment identical in both cases, or was there maybe some inadvertent up/downgrade of dependencies when downgrading to `0.8.3`?

**Comment by ruhanaazam** [comment] 2024-01-23 19:32
Sorry, you're correct that other versions were changed. Here are the current versions being used:

Botorch: 0.8.3
GPyTorch: 1.10
Pytorch: 1.12.0
Ubuntu 20.04
Python: 3.10.9

**Comment by Balandat** [comment] 2024-01-24 15:08
Hmm interesting that this also involved a pytorch downgrade. Anyway, this is a rather old botorch version (latest is 0.9.5) and I've not able to reproduce the issue on that one, so I'll close this issue for now. If you can, I suggest you try the most recent version as well.

**Closed by Balandat** 2024-01-24 15:08 UTC
Labels: bug
