### ISSUE TITLE
Memory not freed after a gp model is discarded [Bug]

### ISSUE THREAD

**Issue by wjp97** [pytorch/botorch#1585] opened 2022-12-22 05:49 UTC
# 🐛 Bug

Iteratively creating  gp models and doing forward pass in each iteration will result in out of memory.  
## To reproduce
```
import torch
from botorch.acquisition.analytic import ExpectedImprovement
from botorch.models.gp_regression import SingleTaskGP

def create_gp_forward(do_acq, device):

    # create the training data
    train_X = torch.rand(4096, 2).to(device)
    train_Y = torch.sin(train_X).sum(dim=1, keepdim=True).to(device)

    # creating the gp model
    gp = SingleTaskGP(train_X, train_Y)
    gp.to(device)

    gp(train_X)

    if do_acq:
        with torch.no_grad():
            test_X = torch.rand(4096, 1, 2).to(device)
            acq_func = ExpectedImprovement(model=gp, best_f=1.0).to(device)
            acq_val = acq_func(test_X).cpu().detach()

    print(torch.cuda.memory_summary(device=device).split("\n")[7])

if __name__ == "__main__":
    for _ in range(10000):
        create_gp_forward(do_acq=True, device = "cuda")
```
** Code snippet to reproduce **
```python
# Your code goes here
# Please make sure it does not require any external dependencies
```

** Stack trace/error message **
The memory allocated on GPU  keeps growing. 
```
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  265480 KB |     896 MB |    2643 MB |    2383 MB |
| Allocated memory      |  530928 KB |    1155 MB |    5286 MB |    4767 MB |
| Allocated memory      |     777 MB |    1414 MB |    7929 MB |    7151 MB |
| Allocated memory      |  265480 KB |    1414 MB |   10572 MB |   10313 MB |
| Allocated memory      |  530928 KB |    1414 MB |   13216 MB |   12697 MB |
| Allocated memory      |  530928 KB |    1414 MB |   15859 MB |   15340 MB |
| Allocated memory      |     777 MB |    1414 MB |   18502 MB |   17724 MB |
| Allocated memory      |     777 MB |    1414 MB |   21145 MB |   20367 MB |
| Allocated memory      |    1036 MB |    1674 MB |   23788 MB |   22751 MB |
| Allocated memory      |    1036 MB |    1674 MB |   26432 MB |   25395 MB |
| Allocated memory      |    1296 MB |    1933 MB |   29075 MB |   27779 MB |
| Allocated memory      |    1296 MB |    1933 MB |   31718 MB |   30422 MB |
| Allocated memory      |    1555 MB |    2192 MB |   34361 MB |   32806 MB |
| Allocated memory      |    1555 MB |    2192 MB |   37004 MB |   35449 MB |
| Allocated memory      |    1814 MB |    2451 MB |   39648 MB |   37833 MB |
| Allocated memory      |    1814 MB |    2451 MB |   42291 MB |   40476 MB |
| Allocated memory      |    2073 MB |    2710 MB |   44934 MB |   42860 MB |
| Allocated memory      |    2073 MB |    2710 MB |   47577 MB |   45503 MB |
| Allocated memory      |    2333 MB |    2970 MB |   50220 MB |   47887 MB |
| Allocated memory      |    2333 MB |    2970 MB |   52864 MB |   50531 MB |
| Allocated memory      |    2592 MB |    3229 MB |   55507 MB |   52915 MB |
| Allocated memory      |    2592 MB |    3229 MB |   58150 MB |   55558 MB |
| Allocated memory      |    2851 MB |    3488 MB |   60793 MB |   57942 MB |
| Allocated memory      |    2851 MB |    3488 MB |   63437 MB |   60585 MB |
| Allocated memory      |    3110 MB |    3747 MB |   66080 MB |   62969 MB |
| Allocated memory      |    3110 MB |    3747 MB |   68723 MB |   65612 MB |
| Allocated memory      |    3369 MB |    4007 MB |   71366 MB |   67996 MB |
| Allocated memory      |  530928 KB |    4007 MB |   74009 MB |   73491 MB |
| Allocated memory      |     777 MB |    4007 MB |   76653 MB |   75875 MB |
| Allocated memory      |     777 MB |    4007 MB |   79296 MB |   78518 MB |
| Allocated memory      |    1036 MB |    4007 MB |   81939 MB |   80902 MB |
| Allocated memory      |    1036 MB |    4007 MB |   84582 MB |   83545 MB |
| Allocated memory      |    1296 MB |    4007 MB |   87225 MB |   85929 MB |
| Allocated memory      |    1296 MB |    4007 MB |   89869 MB |   88572 MB |
| Allocated memory      |    1555 MB |    4007 MB |   92512 MB |   90956 MB |
| Allocated memory      |    1555 MB |    4007 MB |   95155 MB |   93600 MB |
| Allocated memory      |    1814 MB |    4007 MB |   97798 MB |   95984 MB |
......
RuntimeError: CUDA out of memory. Tried to allocate 1.52 GiB (GPU 1; 31.75 GiB total capacity; 27.46 GiB already allocated; 761.19 MiB free; 27.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

## Expected Behavior

There should little memory occupied after each iteration of the function `create_gp_forward` because no Tensor will be used afterwards. 
## System information
**Please complete the following information:**
- 0.7.3
- 1.9.0
- 1.12.1
- CentOS7.9

**Comment by wjp97** [comment] 2022-12-22 06:05
Removing either `gp(train_X)` or `acq_val = acq_func(test_X).cpu().detach()` still results in CUDA out of memory. If I only create the gp model and do not do anything related to the forward pass, there will be no out of memory errors.

**Comment by saitcakmak** [comment] 2022-12-22 06:20
Thanks for flagging! I can reproduce the issue -- we will take a closer look tomorrow.

> If I only create the gp model and do not do anything related to the forward pass, there will be no out of memory errors.

This makes me suspect some caches like `train_train_covar` (in GPyTorch) not being released. Pretty much no large tensors get created until we call the model -- and almost all of these tensors get cached in GPyTorch at some level --, so it can really be any number of things. 

cc @esantorella who debugged a memory leak with some other model before

**Comment by saitcakmak** [comment] 2022-12-22 06:40
It looks like I can avoid the OOM if I use a smaller train data size, in which case the allocated memory climbs up to some point then gets freed (and repeats). Which makes me suspect that this is an issue with garbage collection being a bit too lazy. To test this, I just added a `gc.collect()` into `create_gp_forward` which eliminated the OOM. With `gc.collect` in the loop, the allocated memory is constant after each execution of `create_gp_forward`.

Closing this as a garbage collection issue.

**Closed by saitcakmak** 2022-12-22 06:40 UTC
Labels: bug

**Comment by Balandat** [comment] 2022-12-22 15:11
Not that this would be a "fix", just curious about the underlying causes here.

**Comment by esantorella** [comment] 2022-12-22 16:52
Yeah, I'm also curious about the root cause here and assigning this to myself to look into. I've seen peculiarly slow garbage collection in similar situations but on a CPU myself. It's possible that something like [this](https://stackoverflow.com/questions/22440421/python-is-the-garbage-collector-run-before-a-memoryerror-is-raised) is happening. 

If that's the case, a shallow fix would be using `gc.set_threshold` to set lower thresholds, and a deeper fix would be refactoring references so that it's easier for the garbage collector to spot what should be deallocated.

**Comment by Balandat** [comment] 2022-12-22 17:16
Yeah breaking reference cycles seems like the right thing to do - though it might end up being rather challenging to do that given the complexity of the stack at this point. But certainly worth an initial investigation. 

Here is an old post that some quick search on this surfaced: https://www.kylev.com/2009/11/03/finding-my-first-python-reference-cycle/

**Comment by esantorella** [comment] 2023-01-07 04:08
This has the same root cause as #641 : memory usage gets really high when calling [`MaternKernel.forward`](https://github.com/cornellius-gp/gpytorch/blob/0fc5408e0aa98b7fa6705e4d21c13068b4e5b1b6/gpytorch/kernels/matern_kernel.py#L86) and GPyTorch [`sq_dist`](https://github.com/cornellius-gp/gpytorch/blob/0fc5408e0aa98b7fa6705e4d21c13068b4e5b1b6/gpytorch/kernels/kernel.py#L26) because several kernel-sized tensors are getting created, and memory for tensors tend to be slow to be freed. After running just one iteration of the function in the OP, there are 10 different tensors of size at least 4096x4096, 16 MB each. See explanation [here](https://github.com/pytorch/botorch/issues/641#issuecomment-1371105207).

Since the issue stems from `MaternKernel`, this is more appropriately a GPyTorch issue.

Possible fix 1: Call `gc.collect()` after each kernel evaluation. I think that would prevent OOMing after repeated iterations. `gc.collect()` can be slow, so we might want to do that only when tensors are over a certain size. However, in examples like the one in #641 this doesn't prevent the process from reserving a lot of memory (even if it isn't occupied by Python objects), and peak memory usage during `MaternKernel.forward` would still be high.

Possible fix 2: Rewrite `MaternKernel.forward` to use in-place operations, at least in a no-grad context, so we completely avoid repeatedly creating and destroying any tensors of substantial size. (Combining in-place operations with Autograd is [discouraged](`MaternKernel.forward`).) That might look ugly but could drastically reduce usage for cases where we're doing a lot of acquisition function evaluations.

Partial fix: Replace `sq_dist` with `torch.cdist`. See discussions [here](https://github.com/pytorch/pytorch/pull/25799). This reduces memory usage
