### ISSUE TITLE
[Question]Multidimensional data prediction with MultiTaskGP model

### ISSUE THREAD

**Issue by zhaojingyao** [pytorch/botorch#500] opened 2020-07-31 06:57 UTC
I download the latest gpytorch-master and /pytorch/botorch-master to my WIN10, and install them with command ‘python setup.py install’. Then I run mycode_mt.py, the predicted outputs of two tasks are still the same.

Could you please try my code and give me some advice? Maybe something is wrong with my code.

Here is my code:
[mycode_mt.txt](https://github.com/pytorch/botorch/files/5005570/mycode_mt.txt)

Thanks!

**Comment by Balandat** [comment] 2020-07-31 13:45
Duplicate of #497.

**Closed by Balandat** 2020-07-31 13:45 UTC
Labels: bug
