### ISSUE TITLE
Minimal pytorch version not working

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#2082] opened 2023-11-06 15:34 UTC
# 🐛 Bug

By chance, I had still an old pytorch version on my macbook (1.13.1) which is the minimal one needed for botorch based on the recent `requirements.txt`. Running the test suite of the most recent main branch version resulted in several errors for example in `test_logei.py` where it was complaining above an invalid argument type in the `squeeze` operation.

As I have already updated my env to a pytorch 2.x version, I can currently not reproduce it, but if needed I can roll back.

The suggested fix would be to just enforce as minimal version a pytorch 2.x version ...

**Comment by Balandat** [comment] 2023-11-06 15:40
Thanks for flagging. This should have been caught by our integration tests, let me figure out why that wasn't the case.

**Comment by Balandat** [comment] 2023-11-06 15:49
Are you on py3.11? One issue is that pytorch doesn't actually have a Mac binary for 1.3.1 for py 3.11: https://github.com/pytorch/botorch/blob/main/.github/workflows/test_stable.yml#L80-L81

**Comment by jduerholt** [comment] 2023-11-06 15:54
No, it is 3.10 ..., but perhaps it was just my env ..., if you cannot reproduce, then we just ignore it ...

**Comment by Balandat** [comment] 2023-11-06 16:09
I can reproduce :( 

Looks like these are all due to a call to `squeeze()` with `tuple` arg in `_inf_max_helper` that is part of the new logEI functionality. Unfortunately this isn't just in the tests but the botorch code itself. 

I am not sure why this wasn't caught by our CI, but I'll investigate that. In the meantime, maybe the easiest is to modify that single occurrence and put out a quick fix version 0.9.4 (and bump the min req pytorch as part of 0.10.0). 

cc @SebastianAment

**Comment by jduerholt** [comment] 2023-11-06 16:14
Exactly this was also my feeling when running the test suite after updating to the recent version after my parental leave today ..., just the problem in `squeeze`. 

So there will be 0.10.0 and not 1.0.0?

**Comment by Balandat** [comment] 2023-11-06 16:27
> So there will be 0.10.0 and not 1.0.0?

We currently don't have a major set of overhaul features ready that would warrant the jump to 1.0.0 based on semantic versioning. And if we bump the minimum requirements we do at least want to go one up from 0.9. So the natural thing to do is 0.10.0. This is not to say that there won't be a 1.0, just not in the immediate future :)

**Comment by Balandat** [comment] 2023-11-07 00:47
This has been fixed in https://github.com/pytorch/botorch/releases/tag/v0.9.4

Thanks again for flagging.

**Closed by Balandat** 2023-11-07 00:47 UTC
Labels: bug
