### ISSUE TITLE
[Bug] 'symeig_cpu: the algorithm failed to converge' error when using qNEI

### ISSUE THREAD

**Issue by Tenoke** [pytorch/botorch#236] opened 2019-08-13 15:16 UTC
# 🐛 Bug

When using qNEI with SingleTaskGP, sometimes you will run into 
```RuntimeError: symeig_cpu: the algorithm failed to converge; 2 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.```

I believe it happens more often when adding the candidates to your training data.

## To reproduce

[Working Colab example](https://colab.research.google.com/drive/17cwdAwYWTTI-fv0mZ_d4NFsejb5JZxIP)

** Stack trace/error message **

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-54a7133f99a7> in <module>()
     57               model, train_X)
     58   candidates = joint_optimize(
---> 59   qNEI, bounds=bounds, q=1, num_restarts=15, raw_samples=40); print(evaluate(candidates)) #\
     60   train_X = torch.cat([train_X, candidates]) # Add candidate to training data, and retrain

20 frames
/usr/local/lib/python3.6/dist-packages/gpytorch/utils/eig.py in batch_symeig(mat)
     21 
     22     for i in range(batch_shape.numel()):
---> 23         evals, evecs = mat[i].symeig(eigenvectors=True)
     24         mask = evals.ge(0)
     25         eigenvectors[i] = evecs * mask.type_as(evecs).unsqueeze(0)

RuntimeError: symeig_cpu: the algorithm failed to converge; 2 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.
```

## Expected Behavior

for qNEI to give me back a candidate without error-ing

## System information

**Please complete the following information:**

Latest (master) versions of gpytorch and botorch on Google Colab

## Additional context

This issue started appearing around 08.08 for me, possibly because the pytorch version was updated to 1.2.

**Comment by Balandat** [comment] 2019-08-13 15:44
Looking through the nb, the issue seems to be the following:

```
/usr/local/lib/python3.6/dist-packages/gpytorch/lazy/lazy_tensor.py:1327: UserWarning: Runtime Error when computing Cholesky decomposition: CUDA error: invalid device function.
```

Not sure where this is coming from, I haven't seen this kind of error before. The problem is that b/c of this error no jitter is added to the pretty much singular covariance matrix, which means that the root decomposition fails. I was able to run all iterations in the following notebook without this error (instead jitter is added to the covariance matrix and the Cholesky decomposition succeeds): https://colab.research.google.com/drive/1rekgHfpXvrPknIuZN81nU6yGhBTLYhgQ#scrollTo=wiePwhx7S9nl

Maybe some issue with the GPU settings in the colab nb? I'm not very familiar with these. 

Also, can you confirm what torch version is used in your nb? In my copy the pip install also installs the following torch, which is missing from yours: 

```
Downloading https://files.pythonhosted.org/packages/30/57/d5cceb0799c06733eefce80c395459f28970ebb9e896846ce96ab579a3f1/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (748.8MB)
```

**Comment by Tenoke** [comment] 2019-08-13 15:56
It didn't show up because I did a `restart and run all` without resetting so it had downloaded it before. I just reset, so that install is in there but the issue is still there.

Fwiw, the issue doesn't happen all the time. You can get lucky and not see it in 50 steps, by hundred you usually do (at least in Colab). 

I can't see your notebook, you need to get a shareable link from the top right.

**Comment by Tenoke** [comment] 2019-08-13 16:03
Running this on the CPU in Colab does seem to work.

The warnings you get are
```
/usr/local/lib/python3.6/dist-packages/botorch/optim/optimize.py:275: BadInitialCandidatesWarning: Unable to find non-zero acquisition function values - initial conditions are being selected randomly.
  BadInitialCandidatesWarning,
/usr/local/lib/python3.6/dist-packages/gpytorch/utils/cholesky.py:42: RuntimeWarning: A not p.d., added jitter of 1e-06 to the diagonal
  warnings.warn(f"A not p.d., added jitter of {jitter_new} to the diagonal", RuntimeWarning)
tensor([-1.5470e+08])
```
which at least shows jitter is added in that case.

**Comment by Balandat** [comment] 2019-08-13 16:12
Yeah and I was able to successfully run this on GPU in colab as well. The `CUDA error: invalid device function` error suggests there is something funky going on with the GPU setup. Maybe it's also a device-specific issue - might be worth changing the runtime or test locally on a GPU machine.

**Comment by vishwakftw** [comment] 2019-08-15 23:53
The `invalid device function` error could be possible due to a mismatch in MAGMA and CUDA versions, so you might want to check that.

**Comment by Tenoke** [comment] 2019-09-18 10:49
This error is now occuring on CPU, too. Warnings beforehand:

```
/usr/local/lib/python3.6/dist-packages/gpytorch/utils/cholesky.py:42: RuntimeWarning: A not p.d., added jitter of 9.999999999999999e-06 to the diagonal
  warnings.warn(f"A not p.d., added jitter of {jitter_new} to the diagonal", RuntimeWarning)
Iter 10/100: 79332630528.0
Iter 20/100: 64688443392.0
Iter 30/100: 55134167040.0
Iter 40/100: 48599748608.0
Iter 50/100: 43900030976.0
Iter 60/100: 40356012032.0
Iter 70/100: 37572460544.0
Iter 80/100: 35312480256.0
Iter 90/100: 33428750336.0
Iter 100/100: 31825625088.0
/usr/local/lib/python3.6/dist-packages/gpytorch/lazy/lazy_tensor.py:1330: UserWarning: Runtime Error when computing Cholesky decomposition: cholesky_cpu: For batch 0: U(69,69) is zero, singular U.. Using RootDecomposition.
  "Runtime Error when computing Cholesky decomposition: {}. Using RootDecomposition.".format(e)
/usr/local/lib/python3.6/dist-packages/gpytorch/lazy/lazy_tensor.py:1330: UserWarning: Runtime Error when computing Cholesky decomposition: cholesky_cpu: For batch 0: U(1,1) is zero, singular U.. Using RootDecomposition.
  "Runtime Error when computing Cholesky decomposition: {}. Using RootDecomposition.".format(e)
```

Traceback:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-1bae64f94c45> in <module>()
      1 
----> 2 acq_results_1cs = feval.test_models(models, d=8, num_starting=30, n_candidates=250, maximize=True, functions=['svilen', 'rastrigin', 'zakharov', 'dixonpr'], candidates_per_step=1)
      3 with open('/content/drive/My Drive/gp-res/acq_results-d12,s30,c100,1cs', 'wb') as f:
      4   pickle.dump(acq_results_1cs, f)
      5 

25 frames
/usr/local/lib/python3.6/dist-packages/gpytorch/utils/eig.py in batch_symeig(mat)
     21 
     22     for i in range(batch_shape.numel()):
---> 23         evals, evecs = mat[i].symeig(eigenvectors=True)
     24         mask = evals.ge(0)
     25         eigenvectors[i] = evecs * mask.type_as(evecs).unsqueeze(0)

RuntimeError: symeig_cpu: the algorithm failed to converge; 2 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.```

**Comment by Balandat** [comment] 2019-09-18 14:47
Hmm so the fact that you get the following warning without the "adding jitter" warning of `psd_safe_cholesky` makes me think that there are NaNs in the matrix that is being eigendecomposed:

```
/usr/local/lib/python3.6/dist-packages/gpytorch/lazy/lazy_tensor.py:1330: UserWarning: Runtime Error when computing Cholesky decomposition: cholesky_cpu: For batch 0: U(69,69) is zero, singular U.. Using RootDecomposition. "Runtime Error when computing Cholesky decomposition: {}. Using RootDecomposition.".format(e)
```

Looking through the colab example notebook again, I can confirm that this is the case when things error out. The main issue appears to be that your training data isn't being normalized (I'm seeing `Y`s of magnitude `>1e9`), which will result in all kinds of numerical issues.

Can you make sure to normalize your features to the unit cube and standardize (zero mean, unit variance) your training inputs (you can use `normalize` and `standardize`from `botorch.utils.transforms` for this)? I'm about to add some validation for this in #267 to remove this gotcha. 

As an aside: PyTorch has support for batched eigendecomposition since 1.2.0, so we removed the `batch_symeig` function from gpytorch after the 0.3.5. release. There were a few other fixes in the LazyTensor stack since then - we hope to put out new versions with these changes soon, but in the meantime it may make sense to run this on master. The main issue seems to be normalization/standardization.

**Comment by Balandat** [comment] 2019-11-28 16:37
We haven't been seeing these errors for a while now, so I'm going to close this for now, feel free to reopen if necessary. 

Note also that #327 is about to make the normalization/standardization (and respective un-transformations) much easier.

**Closed by Balandat** 2019-11-28 16:37 UTC
Labels: bug
