### ISSUE TITLE
[Bug] Issue with custom GP model

### ISSUE THREAD

**Issue by conan19842002** [pytorch/botorch#691] opened 2021-02-17 10:59 UTC
# 🐛 Bug

In my case, when building a custom GP model, I get an error forward() missing 1 required positional argument: 'x'.
## To reproduce

** Code snippet to reproduce **
```python

import math
from math import floor
import gpytorch
from gpytorch.kernels import Kernel, LinearKernel, MaternKernel
from numpy import ndarray
from botorch.models.gpytorch import GPyTorchModel
from gpytorch.distributions import MultivariateNormal
from gpytorch.means import ConstantMean
from gpytorch.models import ExactGP
from gpytorch.kernels import RBFKernel, ScaleKernel
from gpytorch.likelihoods import GaussianLikelihood
from gpytorch.mlls import ExactMarginalLogLikelihood
from gpytorch.priors import GammaPrior
from botorch.cross_validation import batch_cross_validation
from botorch.cross_validation import gen_loo_cv_folds

def distance_matrix2(x1, x2):
    """Calculate the difference between each input vector x"""
    return x1.view(-1, 1) - x2.view(1, -1).float()

class GenSquaredExponetialKernel(Kernel):
    has_lengthscale = False

    def __init__(self, s1, s2, l1 , l2, log_transformed = False, **kwargs):
        
        if isinstance(s1, ndarray):
            self.s1 = torch.tensor(s1, dtype=torch.float)
        elif torch.is_tensor(s1):
            self.s1 = s1
        else:
            raise TypeError(f"variance is expected to be an array or tensor. "
                            f"Got {type(s1)} instead.")
        if isinstance(s2, ndarray):
            self.s2 = torch.tensor(s2, dtype=torch.float)
        elif torch.is_tensor(s2):
            self.s2 = s2
        else:
            raise TypeError(f"variance is expected to be an array or tensor. "
                            f"Got {type(s2)} instead.")
            
        if isinstance(l1, ndarray):
            self.l1 = torch.tensor(l1, dtype=torch.float)
        elif torch.is_tensor(l):
            self.l1 = l1
        else:
            raise TypeError(f"lengthscale is expected to be an array or tensor. "
                            f"Got {type(l1)} instead.")

        if isinstance(l2, ndarray):
            self.l2 = torch.tensor(l2, dtype=torch.float)
        elif torch.is_tensor(l):
            self.l2 = l2
        else:
            raise TypeError(f"lengthscale is expected to be an array or tensor. "
                            f"Got {type(l2)} instead.")


        if log_transformed:
          self.l1 = torch.exp(self.l1).double()
          self.l2 = torch.exp(self.l2).double()
          self.s1 = torch.exp(self.s1).double()
          self.s2 = torch.exp(self.s2).double()
        super(GenSquaredExponetialKernel, self).__init__(**kwargs)
    
    def forward(self, x1, x2, diag=False, **params):
        
        n_features = x1.size()[1]

        first_comp = 1
        second_comp = 0
        for i in range(n_features):
          s = torch.pow(self.l1[i].view(-1,1), 2) + torch.pow(self.l2[i].view(1,-1), 2)
          first_comp *= torch.sqrt(torch.div(2*self.l1[i].view(-1,1)*self.l2[i].view(1,-1) ,s ))
          dist = self.covar_dist(x1[:,i:i+1], x2[:,i:i+1], square_dist=True, diag=diag, **params)
         
          f = dist / s
         
          second_comp += f   
        
        first_comp *= torch.matmul(self.s1, self.s2.t())
        second_comp = torch.exp(-second_comp)
        k = first_comp * second_comp
        if diag:
            k = k[0]
        return k

class MyBotorchModelGP(ExactGP, GPyTorchModel):

    _num_outputs = 1  # to inform GPyTorchModel API
    
    def __init__(self, s1, s2, l1, l2, train_X, train_Y):
        # squeeze output dim before passing train_Y to ExactGP
        super().__init__(train_X, train_Y.squeeze(-1), GaussianLikelihood())
        
        self.mean_module = ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(GenSquaredExponetialKernel(s1, s2, l1, l2))

        self.to(train_X)  
        
    def forward(self, x):

        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return MultivariateNormal(mean_x, covar_x)      
        
####### Prepare fake data ########
X = torch.randn(1000,4)[:,:-1]
y = X[:,-1]
train_n = int(floor(0.8 * len(X)))
train_x = X[:train_n, :]
train_y = y[:train_n]

test_x = X[train_n:, :]
test_y = y[train_n:]

s1 = np.array([0.1]*3)
s2 = np.array([0.2]*3)
l1 = np.array([3.0]*3)
l2 = np.array([4.0]*3)

sigma = math.sqrt(0.2)
train_y_noise = train_y + sigma * torch.randn_like(train_y)
train_y_var = torch.full_like(train_y_noise, 0.2)
cv_folds = gen_loo_cv_folds(train_X=train_x, train_Y=train_y, train_Yvar=train_y_var)
model = MyBotorchModelGP(s1, s2, l1, l2, train_X=train_x, train_Y=train_y)
# instantiate and fit model
cv_results = batch_cross_validation(
            model_cls=model,
            mll_cls=gpytorch.mlls.ExactMarginalLogLikelihood,
            cv_folds=cv_folds,
     )  
```

** Stack trace/error message **
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-5cd21042cc84> in <module>()
    129             model_cls=model,
    130             mll_cls=gpytorch.mlls.ExactMarginalLogLikelihood,
--> 131             cv_folds=cv_folds,
    132      )  

2 frames
/usr/local/lib/python3.6/dist-packages/gpytorch/module.py in __call__(self, *inputs, **kwargs)
     26 
     27     def __call__(self, *inputs, **kwargs):
---> 28         outputs = self.forward(*inputs, **kwargs)
     29         if isinstance(outputs, list):
     30             return [_validate_module_outputs(output) for output in outputs]

TypeError: forward() missing 1 required positional argument: 'x'
```

## Expected Behavior
I expected no error in this case

## System information

**Please complete the following information:**
GPyTorch Version (run print(gpytorch.__version__))
1.3.1
PyTorch Version (run print(torch.__version__))
1.7.0+cu101
Computer OS
Window 10

**Comment by saitcakmak** [comment] 2021-02-17 14:08
Hi @conan19842002. I can't run the code you shared since it is missing inputs `train_x, train_y, s1, s2, l1, l2`. Would it be possible to share a runnable script, complete with synthetic inputs?

**Comment by conan19842002** [comment] 2021-02-17 14:46
Hi, sorry for the missing part. I've updated with fake data. Please let me know if you can run it

**Comment by saitcakmak** [comment] 2021-02-17 15:15
Thanks for adding the data! The problem is not due to your custom model, it's the use of `batch_cross_validation`. The `model_cls` argument here takes in the class rather than an instance of the class. It will then use this class to create instances of the class.

So, you should replace 
```
cv_results = batch_cross_validation(
            model_cls=model,
            mll_cls=gpytorch.mlls.ExactMarginalLogLikelihood,
            cv_folds=cv_folds,
     )  
```
with
```
cv_results = batch_cross_validation(
            model_cls=MyBotorchModelGP,
            mll_cls=gpytorch.mlls.ExactMarginalLogLikelihood,
            cv_folds=cv_folds,
     )  
```

`batch_cross_validation` will call `model_cls` only with the arguments `train_X, train_Y, train_Yvar`. Your current model definition has required positional arguments `s1, s2, l1, l2` which would lead to an error here. You can fix this by defining a wrapper around `MyBotorchModelGP` like:
```
def get_wrapped_model(s1, s2, l1, l2):
    def wrapped_model(train_X, train_Y):
        return MyBotorchModelGP(s1, s2, l1, l2, train_X, train_Y)
    return wrapped_model
```
and using this as
```
cv_results = batch_cross_validation(
            model_cls=get_wrapped_model(s1, s2, l1, l2),
            mll_cls=gpytorch.mlls.ExactMarginalLogLikelihood,
            cv_folds=cv_folds,
     )  
```
Hope this helps!

**Comment by Balandat** [comment] 2021-02-19 01:50
Closing this for now, feel free to reopen if needed. Thanks for the debugging @saitcakmak

**Closed by Balandat** 2021-02-19 01:50 UTC
Labels: bug
